# Generated by Django 4.2.3 on 2023-10-10 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_author_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('subject', models.CharField(blank=True, max_length=200, null=True)),
                ('text', models.TextField()),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('is_read', models.BooleanField(default=False, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.author')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='users.author')),
            ],
        ),
    ]
