# Generated by Django 4.2.3 on 2023-10-09 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_author_id'),
        ('blogs', '0005_reaction_blog_reaction_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reaction',
            name='comment',
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('description', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.blog')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.author')),
            ],
        ),
    ]
