# Generated by Django 4.2.3 on 2023-10-09 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_author_id'),
        ('blogs', '0006_remove_reaction_comment_comment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reaction',
            unique_together={('owner', 'blog')},
        ),
    ]
