# Generated by Django 4.2.3 on 2023-10-09 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_alter_comment_unique_together_delete_reaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='react',
            field=models.CharField(choices=[('like', 'Like '), ('unlike', 'Unlike')], default='like', max_length=200),
        ),
    ]
