# Generated by Django 4.2.3 on 2023-10-09 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0009_comment_react'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='react',
            field=models.CharField(choices=[('like', 'Like '), ('unlike', 'Unlike')], max_length=200),
        ),
    ]
