# Generated by Django 4.2.3 on 2023-10-09 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0010_alter_comment_react'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='vote_unlike',
            new_name='vote_dislike',
        ),
        migrations.AlterField(
            model_name='comment',
            name='react',
            field=models.CharField(choices=[('like', 'Like '), ('dislike', 'Dislike')], max_length=200),
        ),
    ]
