# Generated by Django 4.2.3 on 2023-10-10 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0011_rename_vote_unlike_blog_vote_dislike_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-vote_like']},
        ),
    ]
