# Generated by Django 4.2.5 on 2023-10-16 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0012_alter_blog_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='react',
            field=models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike')], max_length=200),
        ),
    ]
